### ISSUE TITLE
Crashes when running on a system with Nvidia/Intel cards

### ISSUE THREAD

**Issue by OK2MOP** [ulissesf/qmassa#19]
When trying to run on a system (Ubuntu 22.04) with both NVIDIA and Intel GPUs active, after pressing Tab key the program crashes (both official and git version).

For git version the backtrace is following:

```
thread 'main' panicked at src/app/main_screen.rs:738:37:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: qmassa::app::main_screen::MainScreen::render_dev_stats
   4: qmassa::app::main_screen::MainScreen::render_drm_device
   5: <qmassa::app::main_screen::MainScreen as qmassa::app::Screen>::draw
   6: qmassa::app::App::draw
   7: ratatui::terminal::terminal::Terminal\<B\>::try_draw
   8: qmassa::app::App::run
   9: qmassa::main
```

inxi listing of devices:
```
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: NVIDIA TU117M [GeForce MX450] driver: nvidia v: 535.216.03
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1: 2560x1440~60Hz 2: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.3
```

nvidia-smi info:

![Image](https://github.com/user-attachments/assets/4a34415d-816d-4072-938d-cbcfb75e5107)

I wonder if it is some powersaving issue when the NVIDIA GPU core is not active?
